- name: install pektin
  vars_files:
      - ../environment.yml
  hosts: hcloud_labels_group_main
  remote_user: root
  tasks:
      - name: copy files
        copy:
            src: ../files/
            dest: ~/files/
      - name: clone pektin
        git:
            repo: https://git.y.gy/pektin/pektin-compose
            dest: ~/pektin-compose
            single_branch: yes
      - name: copy pektin-config
        copy:
            src: ../../pektin-config.yml
            dest: ~/files/
