- name: install pektin
  hosts: hcloud_labels_group_main
  remote_user: root
  vars:
      ansible_ssh_private_key_file: /ansible/keys/pektin
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
      - name: run delete script
        shell: cd ~/pektin-compose/ && bash reset.sh || true
      - name: delete old files
        file:
            path: ~/pektin-compose/
            state: absent
      - name: clone pektin
        git:
            repo: https://git.y.gy/pektin/pektin-compose
            dest: ~/pektin-compose/
            force: true
      - name: run delete script
        shell: cd ~/pektin-compose/ && bash reset.sh || true
      - name: stop systemd-resolved
        shell: systemctl disable --now systemd-resolved
      - name: insert nameserver
        shell: echo 'nameserver 1.1.1.1' > /etc/resolv.conf
      - name: copy pektin-config
        copy:
            src: ../../pektin-config.json
            dest: ~/pektin-compose/
      - name: copy files to compose ansible folder
        copy:
            src: ../../.tmp/
            dest: ~/pektin-compose/ansible/.tmp/
      - name: copy hcloud specific index.js
        copy:
            src: ../files/
            dest: ~/files/
      - name: run preinstall for ansible hetzner setup
        shell: cd ~/files/preinstall/ && bash node-instant.sh
