- name: install and run arbeiter
  vars_files:
      - ../environment.yml
  hosts: hcloud_labels_group_sub
  remote_user: root
  tasks:
      - name: copy floating ip script to remote machine
        copy:
            src: "../../.tmp/floating-ips/configure-scripts/{{ansible_facts['hostname']}}-configure-floating-ips.sh"
            dest: ~/
      - name: run configure floating ips script
        shell: "bash ~/{{ansible_facts['hostname']}}-configure-floating-ips.sh"
      - name: run delete script
        shell: bash ~/pektin-compose/reset.sh || true
      - name: delete old files
        shell: rm -rf ~/pektin-compose/ || true
      - name: copy arbeiter script
        copy:
            src: "../../.tmp/arbeiter/{{ansible_facts['hostname']}}.sh"
            dest: ~/
      - name: run arbeiter script
        shell: "bash ~/{{ansible_facts['hostname']}}.sh"
