- name: Create hetzner server
  hosts: localhost
  vars_files:
      - environment.yml
      - hcloud.yml
  tasks:
      - name: add personal ssh key
        hcloud_ssh_key:
            api_token: "{{ token }}"
            name: "{{KEY_NAME}}"
            public_key: "{{lookup('file', '{{LOCAL_KEYFILE}}')}}"
      - name: create nodes
        include: create-single.yml
        loop: "{{nodes | dict2items}}"
        loop_control:
            index_var: i
